# Generated by Django 4.1.3 on 2022-12-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsstory_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('dogs', 'dog'), ('cats', 'cat'), ('pets', 'pet'), ('ANIMALS', 'Animals'), ('FOOD', 'Food')], default='news', max_length=200),
        ),
    ]
