# Generated by Django 4.1.3 on 2022-12-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsstory_options_newsstory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='newsstory',
            options={},
        ),
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='newsCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
